export declare const IN_VIEWPORT_EVENT = "kl-in-vp";
export declare const OUT_VIEWPORT_EVENT = "kl-out-vp";
export declare const MQ_CHANGE_EVENT = "kl-mq-change";
export declare const EVENT_AEM_MODE_CHANGE = "dvag-aem-mode-changed";
export declare const INPUT_CHANGED_EVENT = "dva-input-changed";
export declare const DATE_CHANGED_EVENT = "dva-date-changed";
export declare const SELECTION_CHANGED_EVENT = "dva-selection-changed";
export declare const CHECKED_EVENT = "dva-checked";
export declare const CHANGED_EVENT = "dva-changed";
export declare const LOADED_EVENT = "dva-loaded";
export declare const INPUT_CHANGE_EVENT = "dvag-input-changed";
export declare const CHECKGROUP_CHANGE_EVENT = "dvag-checkgroup-changed";
export declare const TOPICS_GROUP_RENDERED = "dvag-topics-group-rendered";
export declare const MAP_LOADED_EVENT = "dvag-map-loaded";
export declare const MAP_ACTIVE_MARKER_CHANGED_EVENT = "dvag-active-marker-changed";
export declare const SLIDE_ZOOMED_EVENT = "dvag-slide-zoomed";
export declare const OVERLAY_OPEN_EVENT = "dvag-overlay-open";
export declare const OVERLAY_CLOSE_EVENT = "dvag-overlay-close";
export declare const CONSENT_CATEGORY_CHANGED_EVENT = "dva-consent-category-changed";
export declare const CONSENT_MANAGEMENT_READY_EVENT = "dva-consent-management-ready";
export declare const CONSENT_CATEGORIES_AVAILABLE = "dva-consent-category-available";
export interface ConsentCategoryChangedEvent {
    detail: {
        category: string;
        consent: boolean;
    };
}
export declare const COOKIE_CHANGE_EVENT = "dva-cookie-change";
export declare const SLIDE_CHANGED_EVENT = "dva-slide-changed";
export declare const SUBMIT_SUCCESS_EVENT = "dva-submit-success";
export declare const SUBMIT_ERROR_EVENT = "dva-submit-error";
export declare const STEP_CHANGED_EVENT = "dva-step-changed";
export declare const CONTENT_LOADED = "dva-content-loaded";
export declare const ANALYTICS_QUESTIONNAIRE_START_EVENT = "dva-analytics-questionnaire-start";
export declare const ANALYTICS_QUESTIONNAIRE_ABORT_EVENT = "dva-analytics-questionnaire-abort";
export declare const ANALYTICS_QUESTIONNAIRE_RESULT_EVENT = "dva-analytics-questionnaire-result";
export declare const TRACK_YOUTUBE_PLAY = "dvag:youtube-play";
export declare const TRACK_YOUTUBE_PAUSE = "dvag:youtube-pause";
export declare const TRACK_YOUTUBE_SEEKING = "dvag:youtube-seeking";
export declare const TRACK_YOUTUBE_PLAY_PROGRESS_25 = "dvag:youtube-play-progress-25";
export declare const TRACK_YOUTUBE_PLAY_PROGRESS_50 = "dvag:youtube-play-progress-50";
export declare const TRACK_YOUTUBE_PLAY_PROGRESS_75 = "dvag:youtube-play-progress-75";
export declare const TRACK_YOUTUBE_PLAY_PROGRESS_100 = "dvag:youtube-play-progress-100";
export declare const VB_FORM_PANEL_DELETED = "dvag-form-panel-deleted";
export declare const VB_FORM_PANEL_SORT_UP = "dvag-form-panel-sort-up";
export declare const VB_FORM_PANEL_SORT_DOWN = "dvag-form-panel-sort-down";
